stages:
  - ğŸ” test
  - ğŸ“¦ build
  - ğŸ¦Š pages

image: javiersantos/android-ci

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
  - chmod +x ./gradlew

cache:
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - .gradle/

test:
  stage: ğŸ” test
  script:
    - ./gradlew test
  artifacts:
    untracked: true
    reports:
      junit: app/build/test-results/**/*.xml

build:
  stage: ğŸ“¦ build
  script:
    - ./gradlew assemble
  dependencies:
    - test
  artifacts:
    paths:
      - app/build/outputs/apk/

pages:
  stage: ğŸ¦Š pages
  image: debian
  script:
    - mkdir public
    - cp app/build/outputs/apk/release/app-release-unsigned.apk public/
    - cp app/build/outputs/apk/debug/app-debug.apk public/
  dependencies:
    - build
  artifacts:
    paths:
      - public

